export const filters = [
  {
    id: "brand",
    name: "Brand",
    options: [
      { value: "Apple", label: "Apple", checked: false },
      { value: "Samsung", label: "Samsung", checked: false },
      { value: "OPPO", label: "OPPO", checked: false },
      { value: "Huawei", label: "Huawei", checked: false },
      {
        value: "Microsoft Surface",
        label: "Microsoft Surface",
        checked: false,
      },
      { value: "Infinix", label: "Infinix", checked: false },
      { value: "HP Pavilion", label: "HP Pavilion", checked: false },
      {
        value: "Impression of Acqua Di Gio",
        label: "Impression of Acqua Di Gio",
        checked: false,
      },
      { value: "Royal_Mirage", label: "Royal_Mirage", checked: false },
      {
        value: "Fog Scent Xpressio",
        label: "Fog Scent Xpressio",
        checked: false,
      },
      { value: "Al Munakh", label: "Al Munakh", checked: false },
      { value: "Lord - Al-Rehab", label: "Lord - Al-Rehab", checked: false },
      { value: "L'Oreal Paris", label: "L'Oreal Paris", checked: false },
      { value: "Hemani Tea", label: "Hemani Tea", checked: false },
      { value: "ROREC White Rice", label: "ROREC White Rice", checked: false },
      { value: "Fair & Clear", label: "Fair & Clear", checked: false },
      { value: "Saaf & Khaas", label: "Saaf & Khaas", checked: false },
      { value: "Bake Parlor Big", label: "Bake Parlor Big", checked: false },
      {
        value: "Baking Food Items",
        label: "Baking Food Items",
        checked: false,
      },
      { value: "Dry Rose", label: "Dry Rose", checked: false },
      { value: "Boho Decor", label: "Boho Decor", checked: false },
      { value: "Flying Wooden", label: "Flying Wooden", checked: false },
      { value: "LED Lights", label: "LED Lights", checked: false },
      { value: "luxury palace", label: "luxury palace", checked: false },
      { value: "Golden", label: "Golden", checked: false },
    ],
  },
  {
    id: "category",
    name: "Category",
    options: [
      { value: "smartphones", label: "Smartphones", checked: false },
      { value: "laptops", label: "Laptops", checked: false },
      { value: "fragrances", label: "Fragrances", checked: false },
      { value: "skincare", label: "Skincare", checked: false },
      { value: "groceries", label: "Groceries", checked: false },
      { value: "home-decoration", label: "Home Decoration", checked: false },
      { value: "furniture", label: "Furniture", checked: false },
      { value: "tops", label: "Tops", checked: false },
      { value: "womens-dresses", label: "Women's Dresses", checked: false },
      { value: "womens-shoes", label: "Women's Shoes", checked: false },
      { value: "mens-shirts", label: "Men's Shirts", checked: false },
      { value: "mens-shoes", label: "Men's Shoes", checked: false },
      { value: "mens-watches", label: "Men's Watches", checked: false },
      { value: "womens-watches", label: "Women's Watches", checked: false },
      { value: "womens-bags", label: "Women's Bags", checked: false },
      { value: "womens-jewellery", label: "Women's Jewellery", checked: false },
      { value: "sunglasses", label: "Sunglasses", checked: false },
      { value: "automotive", label: "Automotive", checked: false },
      { value: "motorcycle", label: "Motorcycle", checked: false },
      { value: "lighting", label: "Lighting", checked: false },
    ],
  },
  {
    id: "size",
    name: "Size",
    options: [
      { value: "2l", label: "2L", checked: false },
      { value: "6l", label: "6L", checked: false },
      { value: "12l", label: "12L", checked: false },
      { value: "18l", label: "18L", checked: false },
      { value: "20l", label: "20L", checked: false },
      { value: "40l", label: "40L", checked: true },
    ],
  },
];
